security:
    providers:
        oauth:
            id: knpu.oauth2.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            security: false
        command_qotd:
            pattern: ^/command/qotd$
            security: false
        auth:
            pattern: ^/connect/google$
            security: false
        main:
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            # # Uncomment the next two line if you can not login with Google, and comment the previous one
            #     - App\Security\YoloAuthenticator
            # stateless: true

    access_control:
        - { path: ^/, roles: ROLE_USER }
