security:
    providers:
        oauth:
            id: knpu.oauth2.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            security: false
        auth:
            pattern: ^/connect/google$
            security: false
#        main:
#            custom_authenticators:
#                - App\Security\GoogleAuthenticator

    access_control:
        - { path: ^/, roles: ROLE_USER }
