services:
    builder:
        build:
            context: services/php
            target: builder
            cache_from:
                - "type=registry,ref=${REGISTRY:-}/builder:cache"
        depends_on:
            - postgres
        user: "${USER_ID}:${USER_ID}"
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            - UID=${USER_ID}
            - APP_ENV=${APP_ENV:-dev}
            # The following list contains the common environment variables exposed by CI platforms
            - GITHUB_ACTIONS
            - CI # Travis CI, CircleCI, Cirrus CI, Gitlab CI, Appveyor, CodeShip, dsari
            - CONTINUOUS_INTEGRATION # Travis CI, Cirrus CI
            - BUILD_NUMBER # Jenkins, TeamCity
            - RUN_ID # TaskCluster, dsari
            - HOME=/home/app
        volumes:
            - "../..:/var/www:cached"
            - "../../.home:/home/app:cached"
        profiles:
            - default
