volumes:
    postgres-data: {}
    builder-data: {}

services:
    frontend:
        build:
            context: services/php
            target: frontend
            cache_from:
                - "type=registry,ref=${REGISTRY:-}/frontend:cache"
        user: "${USER_ID}:${USER_ID}"
        depends_on:
            postgres:
                condition: service_healthy
        env_file: .env
        volumes:
            - "../..:/var/www:cached"
            - "../../.home:/home/app:cached"
        profiles:
            - default
        labels:
            - "project-name=${PROJECT_NAME}"
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.rule=Host(`${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.tls=true"
            - "traefik.http.services.${PROJECT_NAME}-frontend.loadbalancer.server.port=80"

    postgres:
        image: postgres:16
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        profiles:
            - default

    builder:
        platform: linux/amd64 # imagemin libs are not ARM compatible
        build:
            context: services/php
            target: builder
            cache_from:
                - "type=registry,ref=${REGISTRY:-}/builder:cache"
        init: true
        user: "${USER_ID}:${USER_ID}"
        env_file: .env
        depends_on:
            - postgres
        volumes:
            - "../..:/var/www:cached"
            - "../../.home:/home/app:cached"
        profiles:
            - builder

    cron:
        build:
            context: services/php
            target: cron
            cache_from:
                - "type=registry,ref=${REGISTRY:-}/cron:cache"
        depends_on:
            postgres:
                condition: service_healthy
        env_file: .env
        environment:
            USER_ID: ${USER_ID}
        volumes:
            - "../..:/var/www:cached"
            - "../../.home:/home/app:cached"
        profiles:
            - default
