name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    name: Run the tests suite
    runs-on: ubuntu-latest
    env:
      APP_ENV: 'test'
    steps:
      # Install official version of docker that correctly supports from-cache option in docker compose
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          set-host: true

      # Docker socket path is different when using setup docker
      - name: Set Docker Socket Host
        run: echo "DOCKER_SOCKET_PATH=${DOCKER_HOST:5}" >> $GITHUB_ENV

      - name: Log in to registry
        shell: bash
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Castor
        uses: castor-php/setup-castor@v0.1.0

      - name: "Build and start the infrastructure"
        run: castor start

      - name: CS
        run: castor cs

      - name: PHPStan
        run: castor phpstan

      - name: PHPUnit
        run: castor phpunit
